# Generated by Django 4.2 on 2023-07-08 12:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('image', models.ImageField(blank=True, default='mentors/default.jpg', upload_to='mentors/')),
                ('name', models.CharField(max_length=15)),
                ('about', models.TextField()),
                ('tel', models.URLField()),
                ('course', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=255)),
                ('language', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Русский', 'Русский'), ('Кыргызский', 'Кыргызский')], max_length=20), size=None)),
                ('skils', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), size=None)),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_update', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Mentor',
                'verbose_name_plural': 'Mentors',
            },
        ),
        migrations.CreateModel(
            name='WorkTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daystart', models.CharField(max_length=20)),
                ('dayend', models.CharField(max_length=20)),
                ('weekends', models.CharField(max_length=20)),
                ('weekende', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MentorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='mentors.mentor')),
            ],
        ),
    ]
