# Generated by Django 4.2 on 2023-07-08 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='is_mentor',
        ),
    ]
